export const TODOS_ACTION_TYPES = {
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  DELETE_TODO: 'DELETE_TODO',
  LOADING_TODOS: 'LOADING_TODOS',
  LIST_TODOS: 'LIST_TODOS',
  GET_ERROR: 'GET_ERROR',
};